### ISSUE TITLE
Implementar ILCM-SbS

### ISSUE THREAD

**Issue by miguelarauj1o** [bcgs/ILCM-SbS#1]
Implementar o estimador apresentado na página 878 do artigo a seguir, fazendo
avaliações para o mesmo cenário (quantidade de etiquetas, repetições, quadro
inicial etc) da Figura 4 (implementar somente o ILCM SbS ) e depois de 100 a
1000 etiquetas em passos de 100 etiquetas:
http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7067455&tag=1 O valor de
Q deve ser obtido conforme feito no próprio artigo.

**Comment by brunocgsampaio** [comment]
Done!
